[project]
name = "adventofcode2023"
version = "0.1.0"
description = "Add a short description here"
authors = ["Colin Fuller <colin@cjf.io>"]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tasks]

[dependencies]
python = "==3.12"
